### ISSUE TITLE
Error loading Hourly data with Point

### ISSUE THREAD

**Issue by Diederik98** [meteostat/meteostat-python#101]
With version 1.6.2 I get the following error and it origins from It origins from `meteostat/core/loader.py:load_handler`
```
URL can't contain control characters. '/v2/hourly/YEAR/<meteostat.interface.point.Point object at 0x2b037dcd0>.csv.gz' (found at least ' ')
```

**Comment by gutzbenj** [comment]
Hey there,

I don't know if this is directly related but there seems to be a bug here

https://github.com/meteostat/meteostat-python/blob/1f332834e80276259d7143d2ec35dfcce7053c94/meteostat/utilities/endpoint.py#L28

where it probably should be 

```python
if granularity == Granularity.HOURLY and year: 
```

**Comment by clampr** [comment]
Thank you @gutzbenj for spotting the bug! I'll publish a new release in a bit.

I'm not sure if this is causing your problem @Diederik98. Can you share your script?
