### ISSUE TITLE
Hourly weather data not matching with https://www.wunderground.com/history

### ISSUE THREAD

**Issue by sainir92** [meteostat/meteostat-python#102]
Hi,
I am trying to fetch hourly data for city Northville, Michigan but it's not matching with hourly data given on https://www.wunderground.com/history.
I am using below geocodes and dates to fetch the data, so am I missing something here?
![issue](https://user-images.githubusercontent.com/108313609/176079899-049f1721-5778-4782-8520-074ba37f5a86.JPG)

**Comment by Min-Jiang** [comment]
Same Issue, the TEMP/RHUM not matching with the web records
