### ISSUE TITLE
Terms of service link not working

### ISSUE THREAD

**Issue by FinancialPenguin** [meteostat/meteostat-python#105]
The terms of service link results in a 404-error!
https://github.com/meteostat/meteostat-python/blob/b6727659be4a01c166f197a566eae5bf7dc9ff20/README.md?plain=1#L85

**Comment by clampr** [comment]
I see, it's supposed to be this link: https://dev.meteostat.net/terms.html

Will be changed as part of the next release. Thanks.

**Comment by FinancialPenguin** [comment]
No worries! Happy to help.
