### ISSUE TITLE
Hourly data- Weather Condition code

### ISSUE THREAD

**Issue by revathisujendran86** [meteostat/meteostat-python#116]
Trying to generate hourly data for historical record. Used Normalizer and Interpolation method to fill gaps and remove empty values in weather dataframe. But still I am getting empty dataframe in **Weather condition code -coco** column. Please help me to resolve the issues. How to generate weather data without empty values.

**Comment by clampr** [comment]
Unfortunately, it's not always possible to get rid of those gaps. If there is no data at all for `coco`, we cannot perform adequate interpolation.
