### ISSUE TITLE
station data error?

### ISSUE THREAD

**Issue by paapu88** [meteostat/meteostat-python#121]
Dear Developers,
When I get stations in Finland to csv by:
```
stations = Stations()
stations = stations.region('FI')
stations = stations.fetch()
stations.to_csv('metstat_stations_finland.csv')
```
The row for station 2998 Helsinki Kumpula looks strange, it is in Africa.

> 2998 | Helsinki Kumpula | FI | WJ | 2998 |   | 24 | 25.3 | 0 | Africa/Cairo | 2013-08-05 | 2023-02-02 | 2013-08-07 | 2022-03-26 | 2015-01-01 | 2020-01-01

The correct lat lon is about
```
#    Helsinki-Kumpula:
#      lat: 60.203071
#      lon: 24.961305
```

Additionally lots of stations run by the Finnish meteorological institute are missing.

**Comment by clampr** [comment]
Hi @paapu88,

Strangely, the coordinates for some Finnish weather stations are off. I had that a couple of times already..

If you like you can submit a PR to get this fixed: https://github.com/meteostat/weather-stations

Otherwise, I'll change it myself.

**Comment by paapu88** [comment]
I see, if you can do the job this time, next time I'll do it myself. Thanks
for a great package. Markus

**Comment by clampr** [comment]
Done.
