### ISSUE TITLE
AttributeError: 'Stations' object has no attribute 'nearby'

### ISSUE THREAD

**Issue by jorgmateos** [meteostat/meteostat-python#13]
Hi! I'm just trying to use Python library and I'm getting this error while implementing the 'Getting started' example...

<img width="707" alt="Captura de pantalla 2020-12-20 a las 12 40 54" src="https://user-images.githubusercontent.com/33936930/102712340-c0c19c00-42c0-11eb-8856-e3a4f7810f9b.png">

**Comment by clampr** [comment]
Hi,

I would suggest to run

```
pip install meteostat -U
```

first to confirm you're on the latest version.

The `nearby` method was introduced in version 1.0. Otherwise, which Python version are you running on?

**Comment by jorgmateos** [comment]
That was the issue!! Thanks @clampr   🥳
