### ISSUE TITLE
Data from METAR missing for some stations?

### ISSUE THREAD

**Issue by bram-tv** [meteostat/meteostat-python#141]
(This might not be the best repository to report the issue but I couldn't find a better one..)

Similar to #140, looking at station 06465 (Schaffen, Belgium): it appears data from the METAR report is no longer included in the meteostat data?
I'm not sure yet if this is an isolated station or if this is more generic.. for some stations it does appear to have METAR data..

Looking at 06465 hourly map data:
- until 13 Augustus it used to get data from the ISD datasource (but that appears to be broken since 13 Augustus, see #140)
- between 13 Augustus and 6 October it was getting data from the METAR reports
- starting from 6 October it no longer has measured data

Looking for some METAR reports I could find: [metar-taf.com](https://metar-taf.com/history/EBDT) and that does appear to have recent data...

**Comment by clampr** [comment]
You're right. But I can confirm the data is available in our database. Let's wait for the next export cycle and revisit again.
