### ISSUE TITLE
data type "string" not understood on python package

### ISSUE THREAD

**Issue by WillBaumgardnerVevo** [meteostat/meteostat-python#25]
I am having trouble punning the python package for meteostat, with both my own code, and with the sample code.  This is on meteostat 1.1.1 on pandas 1.1.5.

Here is what I'm trying to run:

`# Import Meteostat library and dependencies
from datetime import datetime
import matplotlib.pyplot as plt
from meteostat import Point, Daily

# Set time period
start = datetime(2018, 1, 1)
end = datetime(2018, 12, 31)

# Create Point for Vancouver, BC
vancouver = Point(49.2497, -123.1193, 70)

# Get daily data for 2018
data = Daily(vancouver, start, end)
data = data.fetch()

# Plot line chart including average, minimum and maximum temperature
data.plot(y=['tavg', 'tmin', 'tmax'])
plt.show()`

This is the error it's returning

`---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-24-43d52a543f4d> in <module>
     12 
     13 # Get daily data for 2018
---> 14 data = Daily(vancouver, start, end)
     15 data = data.fetch()
     16 

/usr/local/anaconda/lib/python3.6/site-packages/meteostat/daily.py in __init__(self, loc, start, end)
    231             self._stations = loc.index
    232         elif isinstance(loc, Point):
--> 233             stations = loc.get_stations('hourly', start, end)
    234             self._stations = stations.index
    235         else:

/usr/local/anaconda/lib/python3.6/site-packages/meteostat/point.py in get_stations(self, granularity, start, end)
     69 
     70         # Get nearby weather stations
---> 71         stations = Stations()
     72         stations = stations.nearby(self.lat, self.lon, self.radius)
     73 

/usr/local/anaconda/lib/python3.6/site-packages/meteostat/stations.py in __init__(self)
    103 
    104         # Get all weather stations
--> 105         self._load()
    106 
    107         # Clear cache

/usr/local/anaconda/lib/python3.6/site-packages/meteostat/stations.py in _load(self)
     88                 self._columns,
     89                 self._types,
---> 90                 self._parse_dates)
     91 
     92             # Add index

/usr/local/anaconda/lib/python3.6/site-packages/meteostat/core.py in _load_handler(self, path, columns, types, parse_dates)
    122                 names=columns,
    123                 dtype=types,
--> 124                 parse_dates=parse_dates)
    125 
    126         except HTTPError:

/usr/local/anaconda/lib/python3.6/site-packages/pandas/io/parsers.py in parser_f(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, escapechar, comment, encoding, dialect, tupleize_cols, error_bad_lines, warn_bad_lines, skipfooter, doublequote, delim_whitespace, low_memory, memory_map, float_precision)
    676         memory_map=memory_map,
    677         float_precision=float_precision,
--> 678         na_filter=na_filter,
    679         delim_whitespace=delim_whitespace,
    680         warn_bad_lines=warn_bad_lines,

/usr/local/anaconda/lib/python3.6/site-packages/pandas/io/parsers.py in _read(filepath_or_buffer, kwds)
    438     )
    439     kwds["compression"] = compression
--> 440 
    441     if kwds.get("date_parser", None) is not None:
    442         if isinstance(kwds["parse_dates"], bool):

/usr/local/anaconda/lib/python3.6/site-packages/pandas/io/parsers.py in __init__(self, f, engine, **kwds)
    785 
    786     Parameters
--> 787     ----------
    788     filepath_or_buffer : str, path object or file-like object
    789         Any valid string path is acceptable. The string could be a URL. Valid

/usr/local/anaconda/lib/python3.6/site-packages/pandas/io/parsers.py in _make_engine(self, engine)
   1012 
   1013         sep = options["delimiter"]
-> 1014         delim_whitespace = options["delim_whitespace"]
   1015 
   1016         # C engine not supported yet

/usr/local/anaconda/lib/python3.6/site-packages/pandas/io/parsers.py in __init__(self, src, **kwds)
   1706 
   1707         to_remove = []
-> 1708         index = []
   1709         for idx in self.index_col:
   1710             i = ix(idx)

pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader.__cinit__()

/usr/local/anaconda/lib/python3.6/site-packages/pandas/core/dtypes/common.py in pandas_dtype(dtype)

TypeError: data type "string" not understood`

**Comment by clampr** [comment]
I'm not sure what causes this problem. Can you try to overwrite the column dtypes at the top of your script?

```py
from meteostat import Stations

Stations._types = 'object'
```
