### ISSUE TITLE
TypeError: '<=' not supported between instances of 'str' and 'datetime.datetime'

### ISSUE THREAD

**Issue by vuew** [meteostat/meteostat-python#26]
While running this Python example from the official documentation:
```
# Import Meteostat library and dependencies
from datetime import datetime
import matplotlib.pyplot as plt
from meteostat import Point, Daily

# Set time period
start = datetime(2018, 1, 1)
end = datetime(2018, 12, 31)

# Create Point for Vancouver, BC
vancouver = Point(49.2497, -123.1193, 70)

# Get daily data for 2018
data = Daily(vancouver, start, end)
data = data.fetch()

# Plot line chart including average, minimum and maximum temperature
data.plot(y=['tavg', 'tmin', 'tmax'])
plt.show()
```
I get the following error:
`TypeError: '<=' not supported between instances of 'str' and 'datetime.datetime'`

**Note:** I have all the dependencies installed as requested in the doc. I didn't get this error a few days ago, I just got it today, maybe it's related to the latest version?

**Comment by clampr** [comment]
Seems like the bug was caused by a Pandas update. Please upgrade to version `1.1.2` and let me know if that solves the problem. You should probably delete the `~/.meteostat` folder before trying again.

**Comment by GangaBisht** [comment]
Hi,

I have updated Pandas package (latest 1.2.3)  and still face the same issue. I even uninstalled and reinstalled the meteostat package.

**Comment by clampr** [comment]
Can you try to re-install Meteostat with:

```sh
pip install meteostat==1.1.2 -U
```

By default, the `.meteostat` folder is located in your home directory (`~`).

**Comment by scmbradley** [comment]
I had this problem and  `rm -rf ~/.meteostat` and `pip install -U meteostat` fixed this issue.

**Comment by GangaBisht** [comment]
Thanks, it worked
