### ISSUE TITLE
Since late last night, I started getting errors running the python package for Meteosat with both my own code and with the sample code when the output of the point() function is used to call the Daily() or Hourly() functions. 

### ISSUE THREAD

**Issue by GangaBisht** [meteostat/meteostat-python#28]
# Set time period
start = datetime(2018, 1, 1)
end = datetime(2018, 12, 31)

# Create Point for Vancouver, BC
vancouver = Point(49.2497, -123.1193, 70)

# Get daily data for 2018
data = Daily(vancouver, start, end)
data = data.fetch()

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-43d52a543f4d> in <module>
     12 
     13 # Get daily data for 2018
---> 14 data = Daily(vancouver, start, end)
     15 data = data.fetch()
     16 

~\anaconda3\lib\site-packages\meteostat\daily.py in __init__(self, loc, start, end)
    231             self._stations = loc.index
    232         elif isinstance(loc, Point):
--> 233             stations = loc.get_stations('hourly', start, end)
    234             self._stations = stations.index
    235         else:

~\anaconda3\lib\site-packages\meteostat\point.py in get_stations(self, granularity, start, end)
     77 
     78         # Apply inventory filter
---> 79         stations = stations.inventory(granularity, (start, end))
     80 
     81         # Apply altitude filter

~\anaconda3\lib\site-packages\meteostat\stations.py in inventory(self, granularity, required)
    238             temp._stations = temp._stations[
    239                 (pd.isna(temp._stations[granularity + '_start']) == False) &
--> 240                 (temp._stations[granularity + '_start'] <= required[0]) &
    241                 (
    242                     temp._stations[granularity + '_end'] +

~\anaconda3\lib\site-packages\pandas\core\ops\common.py in new_method(self, other)
     63         other = item_from_zerodim(other)
     64 
---> 65         return method(self, other)
     66 
     67     return new_method

~\anaconda3\lib\site-packages\pandas\core\arraylike.py in __le__(self, other)
     39     @unpack_zerodim_and_defer("__le__")
     40     def __le__(self, other):
---> 41         return self._cmp_method(other, operator.le)
     42 
     43     @unpack_zerodim_and_defer("__gt__")

~\anaconda3\lib\site-packages\pandas\core\series.py in _cmp_method(self, other, op)
   4976         rvalues = extract_array(other, extract_numpy=True)
   4977 
-> 4978         res_values = ops.comparison_op(lvalues, rvalues, op)
   4979 
   4980         return self._construct_result(res_values, name=res_name)

~\anaconda3\lib\site-packages\pandas\core\ops\array_ops.py in comparison_op(left, right, op)
    241 
    242     elif is_object_dtype(lvalues.dtype):
--> 243         res_values = comp_method_OBJECT_ARRAY(op, lvalues, rvalues)
    244 
    245     else:

~\anaconda3\lib\site-packages\pandas\core\ops\array_ops.py in comp_method_OBJECT_ARRAY(op, x, y)
     53         result = libops.vec_compare(x.ravel(), y.ravel(), op)
     54     else:
---> 55         result = libops.scalar_compare(x.ravel(), y, op)
     56     return result.reshape(x.shape)
     57 

pandas\_libs\ops.pyx in pandas._libs.ops.scalar_compare()

TypeError: '<=' not supported between instances of 'str' and 'datetime.datetime'

**Comment by clampr** [comment]
Please let me know if this helps: https://github.com/meteostat/meteostat-python/issues/26#issuecomment-814146784
