### ISSUE TITLE
KeyError: 'distance'

### ISSUE THREAD

**Issue by gvangelatos** [meteostat/meteostat-python#34]
I have been using the meteostat Python package for a few months now as part of my thesis and this is the first time i run my project after your last update. When i try to get the stations nearby a location i get the error "KeyError: 'distance'". I tried pip install meteostat -U but it did not solve the issue and i have to present my thesis in a month...
This is the code i am running:

stations = Stations()
stations = stations.nearby(coordinates_df[cntry]["Lat"], coordinates_df[cntry]["Long"])
station = stations.fetch(1)
data = Hourly(station, start = confirmed_df.index[0].to_pydatetime() - datetime.timedelta(days=14), end = confirmed_df.index[confirmed_df.index.shape[0]-1].to_pydatetime() + datetime.timedelta(days=1))
data = data.fetch()

When i run this code this is what i get:

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
c:\users\george vangelatos\appdata\local\programs\python\python39\lib\site-packages\pandas\core\indexes\base.py in get_loc(self, key, method, tolerance)
   3079             try:
-> 3080                 return self._engine.get_loc(casted_key)
   3081             except KeyError as err:

pandas\_libs\index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas\_libs\index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas\_libs\hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas\_libs\hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'distance'

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
c:\users\george vangelatos\appdata\local\programs\python\python39\lib\site-packages\pandas\core\generic.py in _set_item(self, key, value)
   3825         try:
-> 3826             loc = self._info_axis.get_loc(key)
   3827         except KeyError:

c:\users\george vangelatos\appdata\local\programs\python\python39\lib\site-packages\pandas\core\indexes\base.py in get_loc(self, key, method, tolerance)
   3081             except KeyError as err:
-> 3082                 raise KeyError(key) from err
   3083 

KeyError: 'distance'

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-19-ed3e358beb4f> in <module>
----> 1 greece_full = createCovidDataFrame("Greece")
      2 greece_full

<ipython-input-18-3cec85e8d8ef> in createCovidDataFrame(cntry)
    794 
    795     stations = Stations()
--> 796     stations = stations.nearby(coordinates_df[cntry]["Lat"], coordinates_df[cntry]["Long"])
    797     station = stations.fetch(1)
    798 

c:\users\george vangelatos\appdata\local\programs\python\python39\lib\site-packages\meteostat\stations.py in nearby(self, lat, lon, radius)
    160 
    161         # Get distance for each stationsd
--> 162         temp.stations['distance'] = temp.stations.apply(
    163             lambda station: distance(station, [lat, lon]), axis=1)
    164 

c:\users\george vangelatos\appdata\local\programs\python\python39\lib\site-packages\pandas\core\frame.py in __setitem__(self, key, value)
   3161         else:
   3162             # set column
-> 3163             self._set_item(key, value)
   3164 
   3165     def _setitem_slice(self, key: slice, value):

c:\users\george vangelatos\appdata\local\programs\python\python39\lib\site-packages\pandas\core\frame.py in _set_item(self, key, value)
   3241         self._ensure_valid_index(value)
   3242         value = self._sanitize_column(key, value)
-> 3243         NDFrame._set_item(self, key, value)
   3244 
   3245         # check if we are modifying a copy

c:\users\george vangelatos\appdata\local\programs\python\python39\lib\site-packages\pandas\core\generic.py in _set_item(self, key, value)
   3827         except KeyError:
   3828             # This item wasn't present, just insert at end
-> 3829             self._mgr.insert(len(self._info_axis), key, value)
   3830             return
   3831 

c:\users\george vangelatos\appdata\local\programs\python\python39\lib\site-packages\pandas\core\internals\managers.py in insert(self, loc, item, value, allow_duplicates)
   1201             value = safe_reshape(value, (1,) + value.shape)
   1202 
-> 1203         block = make_block(values=value, ndim=self.ndim, placement=slice(loc, loc + 1))
   1204 
   1205         for blkno, count in _fast_count_smallints(self.blknos[loc:]):

c:\users\george vangelatos\appdata\local\programs\python\python39\lib\site-packages\pandas\core\internals\blocks.py in make_block(values, placement, klass, ndim, dtype)
   2730         values = DatetimeArray._simple_new(values, dtype=dtype)
   2731 
-> 2732     return klass(values, ndim=ndim, placement=placement)
   2733 
   2734 

c:\users\george vangelatos\appdata\local\programs\python\python39\lib\site-packages\pandas\core\internals\blocks.py in __init__(self, values, placement, ndim)
    140 
    141         if self._validate_ndim and self.ndim and len(self.mgr_locs) != len(self.values):
--> 142             raise ValueError(
    143                 f"Wrong number of items passed {len(self.values)}, "
    144                 f"placement implies {len(self.mgr_locs)}"

ValueError: Wrong number of items passed 9, placement implies 1

**Comment by clampr** [comment]
No worries. This error sounds familiar. Can you please delete the `~/.meteostat` directory and try again?

**Comment by gvangelatos** [comment]
I just did but unfortunately it didn’t solve the issue

**Comment by clampr** [comment]
Ok, lets try the following:

```sh
pip uninstall meteostat
rm -rf ~/.meteostat
pip install meteostat==1.2.0
```

After you've done this, try with the example first:

```py
# Import Meteostat library and dependencies
from datetime import datetime
import matplotlib.pyplot as plt
from meteostat import Point, Daily

# Set time period
start = datetime(2018, 1, 1)
end = datetime(2018, 12, 31)

# Create Point for Vancouver, BC
vancouver = Point(49.2497, -123.1193, 70)

# Get daily data for 2018
data = Daily(vancouver, start, end)
data = data.fetch()

# Plot line chart including average, minimum and maximum temperature
data.plot(y=['tavg', 'tmin', 'tmax'])
plt.show()
```

If the example doesn't work, we know something is wrong with the lib (at least in your environment/OS). In that case, please let me know which OS you're using and if the following command properly downloads the station CSV file:

```sh
curl "https://bulk.meteostat.net/v2/stations/meta/lib.csv.gz" --output "stations.csv.gz"
```

**Comment by gvangelatos** [comment]
i tried what you said. The same error appears when i try to run the example after the proposed steps. The curl command works and retrieves the stations.csv. I run windows 10 x64

**Comment by clampr** [comment]
I came up with a potential solution caused by a stupid, Windows-specific issue. I don't know it this is it, but please try once more:

```sh
pip install meteostat -U
rm -rf ~/.meteostat
```

**Comment by clampr** [comment]
Alright, we're slowly getting closer 😄  What about this?

```py
from datetime import datetime
import matplotlib.pyplot as plt
from meteostat import Stations, Hourly

# Get a weather station
stations = Stations()
stations = stations.nearby(50, 8)
station = stations.fetch(1)

# Time period
start = datetime(2017, 1, 1)
end = datetime(2017, 1, 1, 23, 59)

# Get hourly data
data = Hourly(station, start, end)
data = data.fetch()

# Plot chart
data.plot(y='temp')
plt.show()
```

Does it show the chart? Do you receive any error message?

**Comment by gvangelatos** [comment]
It seems to be working now! You are awesome!! Thanks so much for taking the time!
