### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'lat'

### ISSUE THREAD

**Issue by slowtoaccept** [meteostat/meteostat-python#35]
Running example on Python 3.85.

from datetime import datetime
import matplotlib.pyplot as plt
from meteostat import Stations, Daily
# Get weather stations ordered by distance to Vancouver, BC
stations = Stations(lat = 49.2497, lon = -123.1193, daily = datetime(2018, 1, 1))
# Fetch closest station (limit = 1)
station = stations.fetch(1)

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-8f80efd58fa4> in <module>
      1 # Get weather stations ordered by distance to Vancouver, BC
----> 2 stations = Stations(lat = 49.2497, lon = -123.1193, daily = datetime(2018, 1, 1))
      3 # Fetch closest station (limit = 1)
      4 station = stations.fetch(1)

TypeError: __init__() got an unexpected keyword argument 'lat'

​

**Comment by clampr** [comment]
You're using an outdated example. Please try as described here: https://dev.meteostat.net/python/api/stations/nearby.html or use [this example](https://dev.meteostat.net/python/#example) to get started.
