### ISSUE TITLE
details of weather condition code not available

### ISSUE THREAD

**Issue by GangaBisht** [meteostat/meteostat-python#36]
Hi,

I am using weather condition code (coco) for my university project. However, the details have gone missing from the below link. Could you please help. 

https://dev.meteostat.net/docs/formats.html#weather-condition-codes

Thanks

**Comment by clampr** [comment]
Please try with this link: https://dev.meteostat.net/formats.html#weather-condition-codes

**Comment by GangaBisht** [comment]
Thanks a lot!!
