### ISSUE TITLE
Weather data at regular intervals 

### ISSUE THREAD

**Issue by CharlieFoxtrotgit** [meteostat/meteostat-python#41]
Disclaimer: I am proposing this enhancement in large part because it would be useful for a personal project that I am currently working on.

For example: a client wishes to obtain daily weather data at Frankfurt Airport for every weekend day in the year 2020. 

Currently, they would have to either make 52 different queries (one for each weekend), or make a single query that would return data for every day of the year. 

I would like to propose an additional method for the Daily and Hourly classes that would allow the client to specify a 'timespan' (in the above case, this would be 2 days) and a 'gap' (in the above case, this would be 5 days) before fetching the dataframe. 

The result might look like this: 

````
from datetime import datetime
from meteostat import Stations, Daily

start = datetime(2020, 1, 4)
end = datetime(2020, 12, 31)

data = Daily('10637', start=start, end=end)
data = data.interval('2D', '5D')
data = data.fetch()

#data contains only 104 rows
````

As for use cases (in addition to my aforementioned project), I could see this feature being useful for comparing weather data year-on-year, or possibly tracking seasonal changes in the weather.

**Comment by clampr** [comment]
I guess you could achieve that with Pandas:

```python
from datetime import datetime
from meteostat import Stations, Daily

start = datetime(2020, 1, 4)
end = datetime(2020, 12, 31)

data = Daily('10637', start, end)
data = data.fetch()
data = data[data.index.dayofweek > 4]
```
