### ISSUE TITLE
Cannot use .bounds().fetch() with the latest version

### ISSUE THREAD

**Issue by guidocioni** [meteostat/meteostat-python#55]
I tried to update meteostat to the latest version but when using `.bounds().fetch()` I always get an empty dataframe. I was able to solve only by going back to 1.2.2. Is this a bug or are there maybe some temporary files/cache files hanging around somewhere? :) 

```python
stations = Stations()
stations = stations.bounds((65, -135), (22, -83))
list_stations = stations.fetch()
list_stations.head()
```

**Comment by clampr** [comment]
I tested your code and it's working for me. Did you try with 1.5.1? Maybe run `rm -rf ~/.meteostat`?

**Comment by guidocioni** [comment]
yep that solved it.
