### ISSUE TITLE
stations.region() does not return every station for a specific region

### ISSUE THREAD

**Issue by FGFischer** [meteostat/meteostat-python#59]
Hello,

I currently am switching from bulkdownloads to meteostat and it makes life much easier.
Unfortunately i encountered a  small issue by accident.

If i use the .region-Function the state "Nordrhein-Westfalen" has 4 Stations. 
`from meteostat import Stations

stations = Stations()
stations = stations.region('DE', 'NW')
print(stations.count())
`

by plotting the stations, combined with a shapefile of the region it looks like this.
![grafik](https://user-images.githubusercontent.com/87119340/124891714-86f48080-dfd9-11eb-8d1d-28b07fccca52.png)

In comparison i plotted Germany, again with the data i got via .regions-Function and NW has more than 4 Stations.
`from meteostat import Stations

stations = Stations()
stations = stations.region('DE', None)
print(stations.count())
`
![grafik](https://user-images.githubusercontent.com/87119340/124898152-3718b800-dfdf-11eb-9cb1-55ee3c21fe39.png)
Edit: highlighted the state by removing the other states.

**Comment by clampr** [comment]
Thanks, good finding @FGFischer! I checked and it seems like most weather stations in NW are labeled with NT for some reason. I will fix this this in github.com/meteostat/weather-stations ASAP.

**Comment by clampr** [comment]
I updated the stations. Should be live within a few hours. 😉
