### ISSUE TITLE
Add Min, Avg & Max humidity in Daily()

### ISSUE THREAD

**Issue by Vhaume** [meteostat/meteostat-python#61]
Hi everyone,

I love using the Python Meteostat API for getting access to meteo data through Daily() function. Unfortunately, Daily() doesn't include Min, average and Max humidity but Hourly() have humidity data. 

Today, if i want to get the min, avg and max humidity data, i have to use Hourly() in order to have the 24 hours data for extract the min, avg and the max data of humidity of the day.

Python code:
hourly_data = Hourly(location, start_date, end_date)
min_humidity = hourly_data.__dict__['_data']['rhum'].min()
avg_humidity = hourly_data.__dict__['_data']['rhum'].avg()
max_humidity = hourly_data.__dict__['_data']['rhum'].max()

Daily() documentation: https://dev.meteostat.net/python/daily.html#api
Hourly() documentation: https://dev.meteostat.net/python/hourly.html#api

Is it possible to add min, avg and max humidity directly in Hourly() result ?

Thank you

**Comment by clampr** [comment]
Hi @Vhaume,

It's true - there's a lack of humidity data in the daily dumps. Same for dew point and weather conditions. While we could certainly add the suggested aggregations, it would come at the cost of performance regression. It's similar to this issue: https://github.com/meteostat/routines/issues/5

With aggregated data we have to decide which parameters matter most. When I built the bulk data interface & the Python lib, I choose the ones which seemed obvious to me. However, I'm aware that this is heavily use case-dependent.

I created an issue #62 for parameter requests/discussion.
