### ISSUE TITLE
Which Parameters Matter Most?

### ISSUE THREAD

**Issue by clampr** [meteostat/meteostat-python#62]
Hi all,

Meteostat supports certain parameters on the `Hourly`, `Daily` and `Monthly` interface which were chosen by myself because I thought they are of common interest. I know that, depending on your use case, you may need different data parameters.

To get an overview of the most-requested parameters for the different interfaces, I would like to get your opinion on what should be included or removed in the future. Please keep in mind that we cannot keep adding more and more parameters as this would lead to a regression of performance. Therefore, we won't be able to support edge cases.

Ideally, I would like to limit the number of parameters to a maximum of 15 by interface. Please vote for your favourites by adding a comment. The checked options are currently included in the respective dumps/interfaces.

### Hourly Data

Hourly data is the highest resolution Meteostat offers. We can only include parameters which are widely supported by our [data sources](https://dev.meteostat.net/sources.html).

- [x] Air temperature (temp)
- [x] Dew point (dwpt)
- [x] Relative humidity (rhum)
- [x] Precipitation total of previous hour (prcp)
- [x] Snow depth (snow)
- [x] Wind direction degrees (wdir)
- [x] Average wind speed of previous hour (wspd)
- [x] Maximum wind gust of previous hour (wpgt)
- [x] Sea-level air pressure (pres)
- [x] Sunshine total of previous hour (tsun)
- [ ] Solar radiation total of previous hour
- [x] Weather condition code (coco)

We could remove either _dwpt_ or _rhum_ (either can be calculated from the other & air temperature) from the dumps (not from the interface) to reduce the dump size. 

### Daily Data

- [x] Average daily air temperature (tavg)
- [x] Minimum daily air temperature (tmin)
- [x] Maximum daily air temperature (tmax)
- [ ] Average daily relative humidity
- [ ] Minimum daily relative humdity
- [ ] Maximum daily relative humidity
- [x] Daily precipitation total (prcp)
- [x] Maximum daily snow depth (snow)
- [x] Average daily wind direction (wdir)
- [x] Average daily wind speed (wspd)
- [x] Maximum daily wind gust (wpgt)
- [x] Average daily sea-level air pressure (pres)
- [x] Daily sunshine total (tsun)
- [ ] Daily solar radiation total

### Monthly Data

- [x] Average monthly air temperature (tavg)
- [x] Average daily minimum air temperature (tmin)
- [x] Average daily maximum air temperature (tmax)
- [ ] Absolute monthly minimum air temperature
- [ ] Absolute monthly maximum air temperature
- [x] Monthly precipitation total (prcp)
- [x] Maximum monthly snow depth (snow)
- [x] Average monthly wind direction (wdir)
- [x] Average monthly wind speed (wspd)
- [x] Maximum monthly wind gust (wpgt)
- [x] Average monthly sea-level air pressure (pres)
- [x] Monthly sunshine total (tsun)
- [ ] Monthly solar radiation total

**Comment by ricl** [comment]
Daily tavg is really tmean if calculated by (tmax+tmin)/2

I would like 3 daily temperature figures, taverage (true average), tmean and tmedian calculated from the hourly figures.

**Comment by clampr** [comment]
> Daily tavg is really tmean if calculated by (tmax+tmin)/2

Actually, `tavg` is defined as the true average, aggregated from 24 hourly observations. So we already have the average and the median (as you suggested by applying `(tmax+tmin)/2`) in the daily dumps.

Only thing we're missing is median. When would you utilize median instead of average/mean when working with temperature data. I'm not a meteorologist, but I mainly see temperature averages being used.

**Comment by ricl** [comment]
Hi Christina,

Unless you have a source that provides such (such as USCRN which is quite
rare), by far and away the majority of reports have tavg created from
(tmin+tmax)/2. Certainly all historical ones do.

It is often mistakenly called tavg when it should be tmean.

Richard

**Comment by ricl** [comment]
Hi Christian,

I have given up on calculating the daily average/median from the hourly
data as hourly records are very limited in scope amongst stations.

The monthly figures are still worth doing from the daily though.

Richard

**Comment by l-kotzur** [comment]
Hey Christian,

great tool! What was the reason you decided against the solar radiation?

Best
Leander

**Comment by clampr** [comment]
Hey Leander,

I didn't actively decide against it. Solar radiation was simply not included in the datasets I was using when I started the project. But I'm actually planning to add solar radiation data. It might take some time, but it's definitely planned :)

**Comment by adriesse** [comment]
Just came across your work, which seems very nice.  I would like to add a couple of votes from my and a few friends for adding solar radiation data (the energy that's running the planet) down to hourly resolution.
