### ISSUE TITLE
The methods are missing return type hints

### ISSUE THREAD

**Issue by Weyaaron** [meteostat/meteostat-python#7]
Since version Version 3.5 Python support type hints for the return type of functions[1].
I'm unsure about their widespread use, but I would encourage using them none the less.

After approval of some people involved in the project, I might fork it and implement the obvious type hints.

Sincerely,
Aaron 

[1]https://docs.python.org/3/library/typing.html

**Comment by clampr** [comment]
Good point. Let's do that!
