### ISSUE TITLE
changing default value for radius in class: Point

### ISSUE THREAD

**Issue by s-razavi** [meteostat/meteostat-python#70]
Thank you for the awesome work.
In the Point class, I see the default values:

    method: str = 'nearest'

    # Maximum radius for nearby stations
    radius: int = 35000

    # Maximum difference in altitude
    alt_range: int = 350

How can we change those? Point does not take the 'radius' keyword argument, or 'method'.

**Comment by clampr** [comment]
You can change the defaults directly after importing:

```py
from meteostat import Point

Point.radius = yourradius
```

**Comment by s-razavi** [comment]
Thank you.

**Comment by edesz** [comment]
Note that `Point` allows the altitude to be set directly [using](https://dev.meteostat.net/python/api/point/#parameters)
```python
from meteostat import Point

altitude = ...
latitude = ...
longitude = ...

reference_point = Point(latitude, longitude, altitude)
```

Also, to find stations within a custom radius, you can [use](https://dev.meteostat.net/python/api/stations/nearby.html#parameters) `Stations`
```python
custom_radius = ...

stations = Stations()
stations = stations.nearby(latitude, longitude, custom_radius)
station = stations.fetch(1)
print(station)
```
