### ISSUE TITLE
Getting ImportError with the provided example

### ISSUE THREAD

**Issue by Jonathan-Gore** [meteostat/meteostat-python#71]
I'm just trying to run the example code from the documentation and I'm running into an ImportError from the first meteostat module call (Point).

`ImportError: cannot import name 'Point' from partially initialized module 'meteostat' (most likely due to a circular import) (c:\git\NOAA Weather\meteostat.py)`

Any ideas what might be causing this?

For context I'm running:
python 3.8.2
conda 4.8.3

I've tried uninstalling/reinstalling with the provided documentation (pip install meteostat) to no effect.

**Comment by clampr** [comment]
You shouldn't call your Python script `meteostat.py` as it interferes with the library. Just rename it to `weather.py` (or anything else) and try again 😉

**Comment by Jonathan-Gore** [comment]
Yay, the second I get home I'll try that!

Makes sense.

Thanks for taking to the time to help troubleshoot!
