### ISSUE TITLE
No weather forecast data available for Romania Country

### ISSUE THREAD

**Issue by PetricaR** [meteostat/meteostat-python#75]
I tried to get some weather data for Romania (Bucharest). Daily weather, actually, and seems, that the API is not working anymore or there is no data available?

**Comment by clampr** [comment]
Hi, data is definitely available for Bucharest: https://meteostat.net/en/place/3LX24L?t=2021-10-01/2021-10-31

Can you share your code?

**Comment by PetricaR** [comment]
# Import Meteostat library and dependencies
from meteostat import Stations, Daily, Hourly
from datetime import datetime
import matplotlib.pyplot as plt
import pandas as pd 
import numpy as np

from meteostat import Stations
stations = Stations()
stations = stations.region('RO')
count = stations.count()

# Show dataframe
station = stations.fetch(count)
station = pd.DataFrame(station)

station[station['daily_end'] > '2021-11-01']

station[station['name'] == 'Bucuresti / Imh']

# Get closest weather station to Romania, RO
from datetime import datetime
import matplotlib.pyplot as plt
from meteostat import Daily

# Time period
start = datetime(2021, 10, 1)
end = datetime(2021, 11, 10)

# Get daily data
data = Daily('15420', start, end)

# Group & aggregate weekly
data = data.normalize().aggregate(freq='1D').fetch()

# Plot chart
data.plot(y=['tavg', 'tmin', 'tmax'])
plt.show()

**Comment by clampr** [comment]
I tried with this code, based on your example:

```py
from meteostat import Daily
from datetime import datetime
import matplotlib.pyplot as plt

start = datetime(2021, 10, 1)
end = datetime(2021, 11, 10)

data = Daily('15420', start, end)
data = data.normalize().aggregate(freq='1D').fetch()

data.plot(y=['tavg', 'tmin', 'tmax'])
plt.show()
```

And it prints the following chart:

![Figure_1](https://user-images.githubusercontent.com/12759785/140192446-81167cae-a020-4569-be3a-172ed1bf6845.png)

**Comment by PetricaR** [comment]
Thank you!
