### ISSUE TITLE
Station providing daily observations, but the hourly ones are Nan

### ISSUE THREAD

**Issue by nantonog** [meteostat/meteostat-python#78]
Hi all,

I am trying to download some hourly precipitation observations from a station (and/or a nearby point), but my output is full of Nans. When I try to download observations for the same period, I get some results.

**Comment by clampr** [comment]
Hi,

Meteostat doesn't solely calculate daily averages from hourly data. It's possible that the interfaces consumed by Meteostat provide only daily data for some stations. Do you have some examples, so I can confirm this isn't a bug?
