### ISSUE TITLE
Python Kernel Crash

### ISSUE THREAD

**Issue by ObiWanLansi** [meteostat/meteostat-python#8]
Hi,
i just tried an little example:
```python
from datetime import datetime
import matplotlib.pyplot as plt
from meteostat import Stations, Daily

# Time period
start = datetime(2018, 1, 1)
end = datetime(2018, 12, 31)

# Get a weather station
stations = Stations()
stations = stations.nearby(49.2497, -123.1193)
```
on Windows 10, Python 3.8.5 -- IPython 7.19.0 (in Spyder 4.1.5) and the Python Kernel Crashes:

```console
Kernel wird neu gestartet... 
Populating the interactive namespace from numpy and matplotlib
[SpyderKernelApp] WARNING | No such comm: 03c8b35f3aec11ebb031b8ca3a73ea1a
```

Have you any idea what's maybe wrong ?

**Comment by clampr** [comment]
Sadly, I cannot tell what's causing this issue. Is it working if you run any of the example scripts in plain Python? Usually, Meteostat should install all dependencies when using pip. Only thing that's an optional dependency is Matplotlib.

**Comment by ObiWanLansi** [comment]
I think matplotlib isn't the problem, I use it almost every day. But what is the PyArrow ? I guess it's an wrapper for Apache Arrow, and i dont know if there is mayve an problem under windows ?

The same python test script worked under Linux Mint 20 (Kernel 5.4.0), also Python 3.8.5 and IPython 7.19.0 and Spyder 4.1.5 **very** fine ... :-) 

It's both an Anaconda Installation and MeteoStat was installed whith pip3 directly from an Konsole (cmd.exe@win / bash@linux)

Maybe I can still test it tonight under a Raspberry ...

**Comment by ObiWanLansi** [comment]
I tried to install it in a Raspberry, but unfortunately had no chance because PyArrow only threw errors.
But of course this is a PyArrow problem and not a MeteoStat problem ....

**Comment by gorogm** [comment]
Same issue here, the example code crashes in the 'stations = Stations()' line :(
Windows 10, Python 3.7.4, conda 4.9.2

**Comment by clampr** [comment]
If PyArrow causes these errors, I'm working on a workaround which is described in #10. I guess we can ship it with the next release.

**Comment by clampr** [comment]
Alright - I finally have an update on this issue. As described in #10 the solution is a workaround for systems which don't support PyArrow.

First, please upgrade to Meteostat 1.0.1:

```sh
pip install meteostat -U
```

If the installation fails, please try again with the `--no-deps` flag and install Pandas manually.

Then, in all scripts that utilize any of the Meteostat classes, simply disable caching:

```py
Stations.max_age = 0
Hourly.max_age = 0
Daily.max_age = 0
```

This will bypass the cache and, therefore, doesn't require PyArrow. I hope it helps some of you.

**Comment by clampr** [comment]
One more update: I decided to drop PyArrow completely as we can achieve similar performance with Pickle. Simply update to Meteostat 1.0.2:

```sh
pip install meteostat -U
```
