### ISSUE TITLE
Weathers' element

### ISSUE THREAD

**Issue by falahfakhri-Iraq** [meteostat/meteostat-python#85]
As a quick search in your nice tool, I didn't find How is it possible to get the other elements such as precipitations, or wind?, 

And, Does this tool cover all the world weathers' stations?

**Comment by clampr** [comment]
Hi, the resulting `DataFrame` should contain information on precipitation and wind. However, it might be some weather stations are missing these parameters.

Yes, Meteostat covers weather stations worldwide. But certainly not all weather stations (yet 😉).

**Comment by falahfakhri-Iraq** [comment]
> Hi, the resulting `DataFrame` should contain information on precipitation and wind.

Thanks a lot for your prompt reply, but I didn't find any example of how to get the data frame csv file of the data! Would you please to clarify, sorry for inconvenience, and also how to get the name of the nearest station that the data comes from?

**Comment by falahfakhri-Iraq** [comment]
I think Australia, is not available, because while I'm looking stations nearby Sydney I'm getting, NA under region, and the country name is Japan, I'd suggest if it possible to add country names, in order to get the name of stations, and there places or big cities.

**Comment by clampr** [comment]
Can you share the code you're using for nearby stations to Sydney?

**Comment by falahfakhri-Iraq** [comment]
Yes sure, These are the code and the results below, 

`# Import Meteostat library

from meteostat import Stations

stations = Stations()
stations = stations.nearby(33.8688, 151.2093)
station = stations.fetch(5)
# Print DataFrame
print(station)`

![image](https://user-images.githubusercontent.com/66899805/154017541-4d0c663b-ac35-4ee7-b5c4-09e9afe1e67d.png)

**Comment by clampr** [comment]
I see. Google doesn't give you decimal degrees.

Please try again with:

```py
from meteostat import Stations

stations = Stations()
stations = stations.nearby(-33.8678, 151.2073)
station = stations.fetch(5)

print(station)
```
