### ISSUE TITLE
Model data when no station nearby

### ISSUE THREAD

**Issue by sramirez** [meteostat/meteostat-python#88]
Hi! 

Congratulations for this amazing repository. I think meteostat could be greatly improved if model data is provided by default if no nearby station is found for a given data point. This happens to me trying to find data in southern Spain as stations are really scarce in some  areas there. As this scenario may appear frequently in certain areas, this new feature could be really cool to add.

**Comment by clampr** [comment]
That would certainly be nice.

However, we'd need to change the way Meteostat works to achieve that. Currently, model data is specifically stored and retrieved only for the locations where a weather station is installed.

Maybe we can set up a grid (e.g. 5 * 5 km) and provide model-based time series for each grid cell. Then, if there are no stations nearby or gaps in the series, we fall back to the closest grid cell.

This would certainly be a milestone that will take some time to implement. But I agree it would improve data availability in remote areas (or those with few stations). Any thoughts?

**Comment by sramirez** [comment]
Just curious, what is/are the source/s for model data?
