### ISSUE TITLE
Get Hourly weather data for a list of dates

### ISSUE THREAD

**Issue by celinahanouti** [meteostat/meteostat-python#89]
Hello, 
Thank you for this useful tool. I have two questions : 

 1. Is it possible to fetch Hourly weather data for a list of datetime for the same location as a bulk? For example, if I want to get Hourly data for the list `[2019-05-01 19:00:00, 2019-05-08 19:00:00, 2019-05-15 19:00:00]` for the same location. 
 2.  If I want to fetch the weather data at this specific time`2019-05-01 19:00:00` for instance, Do the start date and the end date of the `Hourly` class have to have the same value (`2019-05-01 19:00:00` here) ?

Thank you in advance !

**Comment by clampr** [comment]
Hi,

1. That's not supported (yet).
2. Correct. You'll have to pass `datetime(2019, 5, 1, 19)` for both `start` and `end`.
