### ISSUE TITLE
Imputation performs worse!

### ISSUE THREAD

**Issue by couzhei** [meteostat/meteostat-python#95]
Hey everyone,

Thanks for your work, I really like it. The package is very user-friendly and easy to follow. However I have just noticed some strange behaviors when I took a query of `Hourly` data. I directly show my results and the exact latitude and longitude I used.

```Python
!pip install meteostat -q
from datetime import datetime, timedelta
import matplotlib.pyplot as plt
from meteostat import Point, Hourly, Daily

LAT, LON = 36.268548, 50.008506 # this is the exact location of Alborz shopping mall

# Set time period
start = datetime(2018, 1, 1, 0, 0)
end = datetime(2022, 5, 23, 23, 59)

qazvin = Point(LAT, LON)

hourly_data = Hourly(qazvin, start, end)

# hourly_data = hourly_data.normalize()
# hourly_data = hourly_data.interpolate()

hourly_data = hourly_data.fetch()

round(hourly_data.isnull().sum() / hourly_data.shape[0] * 100, 2)
``` 
```bash
>>> 
temp      0.57
dwpt      0.57
rhum      0.57
prcp     75.07
snow    100.00
wdir      3.78
wspd      1.49
wpgt    100.00
pres      1.99
tsun    100.00
coco     92.37
dtype: float64
```
While running after uncommenting both normalization and interpolation, it output:
```
>>>
temp      8.91
dwpt      8.91
rhum      8.91
prcp     77.27
snow    100.00
wdir      8.91
wspd      8.91
wpgt    100.00
pres      8.91
tsun    100.00
coco     83.82
dtype: float64
```
Why is this happening?

**Comment by clampr** [comment]
I suppose this happens because `normalize()` adds `None` values for all missing values according to the frequency. `interpolate()` will only fill gaps up to a certain number of consecutive `None` values. Theoretically, you could do something like `interpolate(9999)` to fill all gaps. But the data quality would be questionable 😉
